#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - curl

runcmd:
  # Instalacja Docker Compose (najnowsza wersja)
  - curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # Dodaj użytkownika 'ubuntu' do grupy docker (bez sudo)
  - usermod -aG docker ubuntu

  # Aktywuj i uruchom usługę Docker
  - systemctl enable docker
  - systemctl start docker

  # Weryfikacja wersji
  - docker --version
  - docker-compose --version


sudo apt update
sudo apt install -y ca-certificates curl gnupg lsb-release

# Dodaj klucz GPG i repo Docker
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Instalacja Docker Engine
sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Upewnij się, że Docker działa
sudo systemctl enable docker
sudo systemctl start docker
docker --version