services:
  cryptoblade:
    container_name: momentum
    image: cryptoblade:latest
    labels:
        - "autoheal=true"
    ports:
        - 8098:80
    environment:
        - CB_TradingBot__AccountName=Demo
        - CB_TradingBot__Accounts__0__Name=Demo
        - CB_TradingBot__Accounts__0__ApiKey=QuchIEfmKQM8sdjPon
        - CB_TradingBot__Accounts__0__ApiSecret=XVMG8nIgRJyR4Rc7v7WLQs6jSN1auL8A7UvS
        - CB_TradingBot__Accounts__0__Exchange=Bybit
        - CB_TradingBot__Accounts__0__IsDemo=true
        - CB_TradingBot__Accounts__1__Name=Qiqi
        - CB_TradingBot__Accounts__1__ApiKey=cT9Qmk7YdOgzNlMkZZ
        - CB_TradingBot__Accounts__1__ApiSecret=4HXCYVzmj7hZc62yXFxlcRjqHBjMxjcldfEa
        - CB_TradingBot__Accounts__1__Exchange=Bybit
        - CB_TradingBot__Accounts__1__IsDemo=false
        - CB_TradingBot__BackTest__End=2025-03-01T00:00:00
        - CB_TradingBot__BackTest__InitialBalance=1000
        - CB_TradingBot__BackTest__InitialUntradableDays=5
        - CB_TradingBot__BackTest__Start=2025-01-01T00:00:00
        - CB_TradingBot__BackTest__StartupCandleData=7.00:00:00
        - CB_TradingBot__Blacklist__0=EOSUSDT
        - CB_TradingBot__BotMode=Live
        - CB_TradingBot__CriticalMode__EnableCriticalModeLong=True
        - CB_TradingBot__CriticalMode__EnableCriticalModeShort=True
        - CB_TradingBot__CriticalMode__WalletExposureThresholdLong=0.3
        - CB_TradingBot__CriticalMode__WalletExposureThresholdShort=0.3
        - CB_TradingBot__DcaOrdersCount=1000
        - CB_TradingBot__DynamicBotCount__MaxDynamicStrategyOpenPerStep=25
        - CB_TradingBot__DynamicBotCount__MaxLongStrategies=50
        - CB_TradingBot__DynamicBotCount__MaxShortStrategies=50
        - CB_TradingBot__DynamicBotCount__Step=00:01:00
        - CB_TradingBot__DynamicBotCount__TargetLongExposure=750
        - CB_TradingBot__DynamicBotCount__TargetShortExposure=750
        - CB_TradingBot__EnableRecursiveQtyFactorLong=True
        - CB_TradingBot__EnableRecursiveQtyFactorShort=True
        - CB_TradingBot__ForceMinQty=False
        - CB_TradingBot__MakerFeeRate=0.0002
        - CB_TradingBot__MaxAbsFundingRate=0.0002
        - CB_TradingBot__MaxRunningStrategies=100
        - CB_TradingBot__MinimumPriceDistance=0.015
        - CB_TradingBot__MinimumVolume=15000
        - CB_TradingBot__MinNormalizedAverageTrueRangePeriod=1
        - CB_TradingBot__MinProfitRate=0.0002
        - CB_TradingBot__NormalizedAverageTrueRangePeriod=14
        - CB_TradingBot__PlaceOrderAttempts=5
        - CB_TradingBot__QtyFactorLong=200
        - CB_TradingBot__QtyFactorShort=200
        - CB_TradingBot__SpotRebalancingRatio=0
        - CB_TradingBot__StrategyName=Momentum
        - CB_TradingBot__StrategySelectPreference=0
        - CB_TradingBot__SymbolMaturityPreference__0=HIGH
        - CB_TradingBot__SymbolVolatilityPreference__0=LOW
        - CB_TradingBot__SymbolVolumePreference__0=HIGH
        - CB_TradingBot__TakerFeeRate=0.00055
        - CB_TradingBot__TradingMode=Dynamic
        - CB_TradingBot__WalletExposureLong=150
        - CB_TradingBot__WalletExposureShort=150
        - CB_TradingBot__Whitelist__0=XRPUSDT
        - CB_TradingBot__Whitelist__4=DOGEUSDT
        - CB_TradingBot__Whitelist__5=ADAUSDT
        - CB_TradingBot__Whitelist__6=SOLUSDT
        - CB_TradingBot__Whitelist__7=TRXUSDT
        - CB_TradingBot__Whitelist__8=MATICUSDT
        - CB_TradingBot__Whitelist__10=DOTUSDT
        - CB_TradingBot__Whitelist__11=BCHUSDT
        - CB_TradingBot__Whitelist__12=SHIB1000USDT
        - CB_TradingBot__Whitelist__13=AVAXUSDT
        - CB_TradingBot__Whitelist__14=UNIUSDT
        - CB_TradingBot__Whitelist__15=XLMUSDT
        - CB_TradingBot__Whitelist__16=LINKUSDT
        - CB_TradingBot__Whitelist__17=XMRUSDT
        - CB_TradingBot__Whitelist__18=ATOMUSDT
        - CB_TradingBot__Whitelist__19=ETCUSDT
        - CB_TradingBot__Whitelist__20=FILUSDT
        - CB_TradingBot__Whitelist__22=HBARUSDT
        - CB_TradingBot__Whitelist__23=LDOUSDT
        - CB_TradingBot__Whitelist__24=CROUSDT
        - CB_TradingBot__Whitelist__25=ARBUSDT
        - CB_TradingBot__Whitelist__26=APTUSDT
        - CB_TradingBot__Whitelist__27=QNTUSDT
        - CB_TradingBot__Whitelist__28=VETUSDT
        - CB_TradingBot__Whitelist__29=NEARUSDT
        - CB_TradingBot__Whitelist__30=MKRUSDT
        - CB_TradingBot__Whitelist__31=AAVEUSDT
        - CB_TradingBot__Whitelist__32=OPUSDT
        - CB_TradingBot__Whitelist__33=GRTUSDT
        - CB_TradingBot__Whitelist__34=SNXUSDT
        - CB_TradingBot__Whitelist__35=ALGOUSDT
        - CB_TradingBot__Whitelist__36=STXUSDT
        - CB_TradingBot__Whitelist__37=EGLDUSDT
        - CB_TradingBot__Whitelist__38=SANDUSDT
        - CB_TradingBot__Whitelist__39=EOSUSDT
        - CB_TradingBot__Whitelist__40=THETAUSDT
        - CB_TradingBot__Whitelist__41=AXSUSDT
        - CB_TradingBot__Whitelist__42=IMXUSDT
        - CB_TradingBot__Whitelist__43=XTZUSDT
        - CB_TradingBot__Whitelist__44=APEUSDT
        - CB_TradingBot__Whitelist__45=MANAUSDT
        - CB_TradingBot__Whitelist__46=FTMUSDT
        - CB_TradingBot__Whitelist__47=BSVUSDT
        - CB_TradingBot__Whitelist__48=RNDRUSDT
        - CB_TradingBot__Whitelist__49=INJUSDT
        - CB_TradingBot__Whitelist__50=CRVUSDT
        - CB_TradingBot__Whitelist__51=NEOUSDT
        - CB_TradingBot__Whitelist__52=FLOWUSDT
        - CB_TradingBot__Whitelist__53=GALAUSDT
        - CB_TradingBot__Whitelist__54=RPLUSDT
        - CB_TradingBot__Whitelist__55=1000XECUSDT
        - CB_TradingBot__Whitelist__56=KAVAUSDT
        - CB_TradingBot__Whitelist__57=1000PEPEUSDT
        - CB_TradingBot__Whitelist__58=CHZUSDT
        - CB_TradingBot__Whitelist__59=KLAYUSDT
        - CB_TradingBot__Whitelist__60=GMXUSDT
        - CB_TradingBot__Whitelist__62=COMPUSDT
        - CB_TradingBot__Whitelist__63=FXSUSDT
        - CB_TradingBot__Whitelist__64=SUIUSDT
        - CB_TradingBot__Whitelist__65=MINAUSDT
        - CB_TradingBot__Whitelist__66=TWTUSDT
        - CB_TradingBot__Whitelist__67=ARUSDT
        - CB_TradingBot__Whitelist__68=CFXUSDT
        - CB_TradingBot__Whitelist__69=DASHUSDT
        - CB_TradingBot__Whitelist__70=DYDXUSDT
        - CB_TradingBot__Whitelist__71=ZILUSDT
        - CB_TradingBot__Whitelist__72=WOOUSDT
        - CB_TradingBot__Whitelist__73=1INCHUSDT
        - CB_TradingBot__Whitelist__74=ENJUSDT
        - CB_TradingBot__Whitelist__75=CVXUSDT
        - CB_TradingBot__Whitelist__76=FLRUSDT
        - CB_TradingBot__Whitelist__77=BATUSDT
        - CB_TradingBot__Whitelist__78=MASKUSDT
        - CB_TradingBot__Whitelist__79=RUNEUSDT
        - CB_TradingBot__Whitelist__80=LRCUSDT
        - CB_TradingBot__Whitelist__81=AGIXUSDT
        - CB_TradingBot__Whitelist__82=QTUMUSDT
        - CB_TradingBot__Whitelist__83=XEMUSDT
        - CB_TradingBot__Whitelist__84=ROSEUSDT
        - CB_TradingBot__Whitelist__85=WLDUSDT
        - CB_TradingBot__Whitelist__86=ZECUSDT
        - CB_TradingBot__Whitelist__87=CELOUSDT
        - CB_TradingBot__Whitelist__88=BLURUSDT
        - CB_TradingBot__Whitelist__89=ENSUSDT
        - CB_TradingBot__Whitelist__90=GMTUSDT
        - CB_TradingBot__Whitelist__91=HNTUSDT
        - CB_TradingBot__Whitelist__92=ILVUSDT
        - CB_TradingBot__Whitelist__93=ASTRUSDT
        - CB_TradingBot__Whitelist__94=HOTUSDT
        - CB_TradingBot__Whitelist__95=YFIUSDT
        - CB_TradingBot__Whitelist__96=FETUSDT
        - CB_TradingBot__Whitelist__97=RVNUSDT
        - CB_TradingBot__Whitelist__98=JSTUSDT
        - CB_TradingBot__Whitelist__99=ANKRUSDT
        - CB_TradingBot__Whitelist__100=ICXUSDT
        - CB_TradingBot__Whitelist__101=KSMUSDT
        - CB_TradingBot__Whitelist__102=SXPUSDT
        - CB_TradingBot__Whitelist__103=BALUSDT
        - CB_TradingBot__Whitelist__104=AUDIOUSDT
        - CB_TradingBot__Whitelist__105=JASMYUSDT
        - CB_TradingBot__Whitelist__106=ETHWUSDT
        - CB_TradingBot__Whitelist__107=IOTXUSDT
        - CB_TradingBot__Whitelist__108=SCUSDT
        - CB_TradingBot__Whitelist__109=ONTUSDT
        - CB_TradingBot__Whitelist__110=IOSTUSDT
        - CB_TradingBot__Whitelist__111=ANTUSDT
        - CB_TradingBot__Whitelist__112=GLMRUSDT
        - CB_TradingBot__Whitelist__113=MAGICUSDT
        - CB_TradingBot__Whitelist__114=BANDUSDT
        - CB_TradingBot__Whitelist__115=SFPUSDT
        - CB_TradingBot__Whitelist__116=OCEANUSDT
        - CB_TradingBot__Whitelist__117=ONEUSDT
        - CB_TradingBot__Whitelist__118=KDAUSDT
        - CB_TradingBot__Whitelist__119=BICOUSDT
        - CB_TradingBot__Whitelist__120=ORDIUSDT
        - CB_TradingBot__Whitelist__121=KNCUSDT
        - CB_TradingBot__Whitelist__122=DGBUSDT
        - CB_TradingBot__Whitelist__123=TOMOUSDT
        - CB_TradingBot__Whitelist__124=ZENUSDT
        - CB_TradingBot__Whitelist__125=SUSHIUSDT
        - CB_TradingBot__Whitelist__126=SSVUSDT
        - CB_TradingBot__Whitelist__127=COREUSDT
        - CB_TradingBot__Whitelist__128=SKLUSDT
        - CB_TradingBot__Whitelist__129=STGUSDT
        - CB_TradingBot__Whitelist__130=LPTUSDT
        - CB_TradingBot__Whitelist__131=UMAUSDT
        - CB_TradingBot__Whitelist__132=JOEUSDT
        - CB_TradingBot__Whitelist__133=EDUUSDT
        - CB_TradingBot__Whitelist__134=CTSIUSDT
        - CB_TradingBot__Whitelist__135=LQTYUSDT
        - CB_TradingBot__Whitelist__136=RSRUSDT
        - CB_TradingBot__Whitelist__137=XNOUSDT
        - CB_TradingBot__Whitelist__138=CKBUSDT
        - CB_TradingBot__Whitelist__139=ACHUSDT
        - CB_TradingBot__Whitelist__140=RDNTUSDT
        - CB_TradingBot__Whitelist__141=RLCUSDT
        - CB_TradingBot__Whitelist__142=MTLUSDT
        - CB_TradingBot__Whitelist__143=OMGUSDT
        - CB_TradingBot__Whitelist__144=API3USDT
        - CB_TradingBot__Whitelist__145=CELRUSDT
        - CB_TradingBot__Whitelist__146=ALPHAUSDT
        - CB_TradingBot__Whitelist__147=RADUSDT
        - CB_TradingBot__Whitelist__148=MAVUSDT
        - CB_TradingBot__Whitelist__149=XVGUSDT
        - CB_TradingBot__Whitelist__150=C98USDT
        - CB_TradingBot__Whitelist__151=SCRTUSDT
        - CB_TradingBot__Whitelist__152=PENDLEUSDT
        - CB_TradingBot__Whitelist__153=ALICEUSDT
        - CB_TradingBot__Whitelist__154=IDUSDT
        - CB_TradingBot__Whitelist__155=CVCUSDT
        - CB_TradingBot__Whitelist__156=DENTUSDT
        - CB_TradingBot__Whitelist__157=LINAUSDT
        - CB_TradingBot__Whitelist__158=SLPUSDT
        - CB_TradingBot__Whitelist__159=STMXUSDT
        - CB_TradingBot__Whitelist__160=PEOPLEUSDT
        - CB_TradingBot__Whitelist__161=CHRUSDT
        - CB_TradingBot__Whitelist__162=NKNUSDT
        - CB_TradingBot__Whitelist__163=RENUSDT
        - CB_TradingBot__Whitelist__164=REQUSDT
        - CB_TradingBot__Whitelist__165=GALUSDT
        - CB_TradingBot__Whitelist__166=COTIUSDT
        - CB_TradingBot__Whitelist__167=GTCUSDT
        - CB_TradingBot__Whitelist__168=GMTUSDT
        - CB_TradingBot__Whitelist__169=HFTUSDT
        - CB_TradingBot__Whitelist__170=SUNUSDT
        - CB_TradingBot__Whitelist__171=SPELLUSDT
        - CB_TradingBot__Whitelist__172=DUSKUSDT
        - CB_TradingBot__Whitelist__173=CTKUSDT
        - CB_TradingBot__Whitelist__174=OGNUSDT
        - CB_TradingBot__Whitelist__175=TUSDT
        - CB_TradingBot__Whitelist__176=STORJUSDT
        - CB_TradingBot__Whitelist__177=AGLDUSDT
        - CB_TradingBot__Whitelist__178=TRBUSDT